### ISSUE TITLE
Videos open automatically if mouse is hovering over them on page load.

### ISSUE THREAD

**Issue by TheCuza** [dessant/youtube-autoplay#11]
**System**

* OS name: Windows
* OS version: 11
* Browser name: Firefox
* Browser version: 114.0
* Extension version: 2.0.0

**Bug description**

1. Open front page of Youtube (or any page with videos on it such as subscriptions page or search results).
2. Before page is finished loading, hover mouse over any video and leave it there without clicking anything.
3. When page is finished loading, video will automatically open as if you had clicked on it.

**Logs**

```
// REPLACE WITH LOGS
```

**Comment by teconas** [comment]
I second this, same Browser and Addon Versions but on Windows 10.
