### ISSUE TITLE
Autoplay Settings for YouTube rejected from the Chrome Web Store

### ISSUE THREAD

**Issue by dessant** [dessant/youtube-autoplay#3]
The extension has been rejected from the Chrome Web Store. Reviewers are taking issue with the description and screenshot of the extension, just like they did during the [Search by Image takedown](https://github.com/dessant/search-by-image/issues/63). I have submitted the extension again for review.

This is the submitted screenshot and description for Autoplay Settings for YouTube 1.0.0:

<p>
  <img width="200" src="https://i.imgur.com/ISZuPKK.png">
</p>

---

Autoplay Settings for YouTube™ is a browser extension that disables the automatic playback of the next video on YouTube, and remembers your autoplay settings between sessions. Disabling autoplay for playlists is also supported.

The continued development of Autoplay Settings for YouTube™ is made possible thanks to the support of awesome backers. If you'd like to join them, please check out https://armin.dev/go/patreon

Autoplay is turned off by default when the extension is installed, and it can be turned on again from YouTube™, or from the extension's options.

The extension is also available for Firefox: https://github.com/dessant/youtube-autoplay#readme

Reviews are not monitored for bug reports, please use GitHub for issues and feature requests.

https://github.com/dessant/youtube-autoplay

YouTube is a trademark of Google Inc. Use of this trademark is subject to Google Permissions.

**Comment by dessant** [comment]
The submission has been rejected with a list of policy violations that do not seem to apply.

---


Chrome Web Store Developer Support <chromewebstore-dev-support@google.com> | Sun, Jan 12, 2020 at 9:17 AM
To: Armin Sebastian <*****@gmail.com>

Dear Developer,

Your Google Chrome item "Autoplay Settings for YouTube™" with ID: aogbgdnkcjgamgglpikcenliinchedel did not comply with our policies and was removed from the Chrome Web Store.

Your item did not comply with the following section of our Program Policies:

"Spam and Placement in the Store"

-  Products must not contain false or misleading information, including in the content, title, icon, description, or screenshots.
-  Descriptions must directly state the functionality of the app so that users can understand the extension they are adding.
- Screenshots must demonstrate the functionality of the extension in action.


Once your item complies with Chrome Web Store policies, you may request re-publication in the Chrome Web Store Developer Dashboard. Your item will be reviewed for policy compliance prior to re-publication.

If you have any questions about this email, please respond and the Chrome Web Store Developer Support team will follow up with you.


Important Note:

Repeated or egregious policy violations in the Chrome Web Store may result in your developer account being suspended or could lead to a ban from using the Chrome Web Store platform.

This may also result in the suspension of related Google services associated with your Google account.


Sincerely,

Chrome Web Store Developer Support

**Comment by dessant** [comment]
I have contacted them and resubmitted the exact same version.

---

Armin Sebastian <*****@gmail.com> | Sun, Jan 12, 2020 at 12:10 PM
To: Chrome Web Store Developer Support <chromewebstore-dev-support@google.com>

Hi,

The description clearly states the functionality and features of the listing, and the screenshot shows the available options, which is the only user interface of the extension.

Your team has been rejecting my extensions several times before, without explaining the exact reason for doing so, and reversing your decisions when things were made public.

[https://github.com/dessant/search-by-image/issues/63](https://github.com/dessant/search-by-image/issues/63)

Not even your colleague at Google, Simeon Vincent, sees why was Search by Image rejected, and they have contacted your team to reinstate the extension.

I have submitted Autoplay Settings for YouTube again for review, and I have created a GitHub issue to document the process.

[https://github.com/dessant/youtube-autoplay/issues/3](https://github.com/dessant/youtube-autoplay/issues/3)

Armin Sebastian

**Comment by dessant** [comment]
Reviewers have approved the previously rejected version.

---

Chrome Web Store Developer Support <chromewebstore-dev-support@google.com> | Sun, Jan 12, 2020 at 7:10 PM
To: Armin Sebastian <*****@gmail.com>

Dear Developer,

Thank you for your item resubmission. Your item will be available in the Chrome Web Store within 30 minutes.

Thank you for your cooperation,

Google Chrome Web Store team

**Comment by zimmertr** [comment]
lol!

**Comment by dessant** [comment]
@zimmertr yeah, by now reviewers have thought me to follow the same script, Video Quality Settings for YouTube was reinstated the same way.

https://github.com/dessant/youtube-video-quality/issues/4
