### ISSUE TITLE
Add-on has not been working the past few months

### ISSUE THREAD

**Issue by Meteor0id** [dessant/youtube-autoplay#7]
Firefox 109.0.1 64

Haven't tested / debugged why it's not working, but can see it isn't working. Videos will auto-play regardless of the settings. I made sure the plugin is enabled and also enabled for private browsing, but that wasn't the issue. Can others confirm?

Hope this project is still active, this is my favorite extension because it doesn't hide the button and provides settings, unlike other similar extensions.

Let me know if I can provide more information

**Comment by Marce1ek** [comment]
same

**Comment by dessant** [comment]
Thanks for the bug report, I'll look into it in the next few days.

**Comment by Marce1ek** [comment]
### **Steps to reproduce the bug**

https://user-images.githubusercontent.com/99329516/224080340-a252e17d-fc00-4097-bcc6-6a1661829493.mp4

**Comment by HerrVincling** [comment]
Sadly the addon is not working for me currently.
The autoplay button does sync with the config tab of the addon, as expected.
![image](https://github.com/dessant/youtube-autoplay/assets/51028676/1590afd7-02d2-48fa-a72c-bd3f31787903)
However, when I refresh the YouTube video, autoplay defaults to being turned on again. When I then refresh the config page, the addon too has it back on.
![image](https://github.com/dessant/youtube-autoplay/assets/51028676/86ae2dfa-5169-490c-91ce-03f241d816da)
I would expected the addon to stay turned off and keep it turned off on YouTube, but it too turns back on (stays in sync).

I have the addon turned on for private browsing, the issue also occurs in non-private windows.
I have Firefox 114.0.1 (64-bit) running on Linux.

I hope this helps, let me know if you need any more info :)
