### ISSUE TITLE
Autoplay button jumping back and forth at random

### ISSUE THREAD

**Issue by Meteor0id** [dessant/youtube-autoplay#8]
**System**

* OS name: [e.g. Windows, Ubuntu] Windows
* OS version: [e.g. 10] 10
* Browser name: [e.g. Chrome, Firefox] Firefox
* Browser version: [e.g. 60]  112.0.2
* Extension version: [e.g. 1.0.0] Ok where am I supposed to find this? The latest version Mozilla has for me.

**Bug description**

The autoplay button is jumping back and forth and random. At first I thought it only happens when I hover over that button but I now think it's happening all the time.

**Logs**

No clue if the following has any relation to this

```
DOMException: Could not parse path (null): NS_ERROR_FILE_UNRECOGNIZED_PATH [MigratorBase.sys.mjs:494:15](resource:///modules/MigratorBase.sys.mjs)
    isSourceAvailable resource:///modules/MigratorBase.sys.mjs:494
```

**Comment by dessant** [comment]
Does it happen during the entire time you watch a video, or when there is a transition between ads and video content, or shortly after the video starts playing?

**Comment by Meteor0id** [comment]
So far it seems to happen the entire time (I block ads by the way)

I will keep my eyes open for the exact circumstances and post here again if I notice anything which might help narrow down the conditions

right now I see it happening even on a paused video and while I am not moving my mouse, and it is jumping at completely random moments with random speeds. Looks like a conflict between something saying "it is on" and something else saying "it is off"

**Comment by dessant** [comment]
Maybe it's a conflict with a different content script, are there any other extensions enabled? What ad blocker are you using?

**Comment by Meteor0id** [comment]
There are other extensions however non of those are aimed at modifying you tubes auto play options.


I am testing out a bunch of plugins here are the ones most likely (but still quite unlikely) to interfere
Adblock
Adblock plus
WebGL Fingerprint defender
CanvasBlocker
Auto Cookie Optout
AudioContext Fingerprint Defender

Note that the autoplay plugin used to work fine in combination with those plugins in the past

**Comment by dessant** [comment]
The Adblock extensions are owned by companies that don't deserve much trust, you could use [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) instead. Please disable all extensions just in case to rule out this type of issue.

If the problem still occurs, please share a YouTube video link too so we can try to reproduce the issue in the same environment.

**Comment by dessant** [comment]
Let's reopen this when the bug can be reproduced in a clean browser profile.
